if (!hasInterface) exitWith {};
_crates = [
    "UK3CB_BAF_Box_40_Ammo",
    "UK3CB_BAF_Box_556_Ammo",
    "UK3CB_BAF_Box_762_Ammo",
    "UK3CB_BAF_Box_Grenade",
    "UK3CB_BAF_Box_L111A1_Ammo",
    "UK3CB_BAF_Box_L134A1_Ammo",
    "UK3CB_BAF_Box_L16_Ammo_HE",
    "UK3CB_BAF_Box_L16_Ammo_Illumination",
    "UK3CB_BAF_Box_L16_Ammo_Mixed",
    "UK3CB_BAF_Box_L16_Ammo_Smoke",
    "UK3CB_BAF_Box_L16_Ammo_WPSmoke",
    "UK3CB_BAF_Box_L7A2_Ammo",
    "UK3CB_BAF_Box_M6_Ammo_HE",
    "UK3CB_BAF_Box_M6_Ammo_Illumination",
    "UK3CB_BAF_Box_M6_Ammo_Mixed",
    "UK3CB_BAF_Box_M6_Ammo_Smoke",
    "UK3CB_BAF_Box_M6_Ammo_WPSmoke",
    "UK3CB_BAF_Box_Milan_Ammo",
    "UK3CB_BAF_Box_Warrior_Ammo",
    "UK3CB_BAF_SupplyCrate_Ammo",
    "UK3CB_BAF_SupplyCrate_L16_Ammo_HE",
    "UK3CB_BAF_SupplyCrate_L16_Ammo_Illumination",
    "UK3CB_BAF_SupplyCrate_L16_Ammo_Mixed",
    "UK3CB_BAF_SupplyCrate_L16_Ammo_Smoke",
    "UK3CB_BAF_SupplyCrate_L16_Ammo_WPSmoke",
    "UK3CB_BAF_Box_L111A1",
    "UK3CB_BAF_Box_L134A1",
    "UK3CB_BAF_Box_L16",
    "UK3CB_BAF_Box_L1A1",
    "UK3CB_BAF_Box_L7A2",
    "UK3CB_BAF_Box_WpsLaunch",
    "UK3CB_BAF_Box_WpsLaunch_ILAW",
    "UK3CB_BAF_Box_WpsLaunch_Javelin",
    "UK3CB_BAF_Box_WpsLaunch_NLAW",
    "UK3CB_BAF_Box_M6",
    "UK3CB_BAF_Box_WpsBasic",
    "UK3CB_BAF_Box_WpsSpecial",
    "UK3CB_BAF_Box_WpsStatic",
    "ACE_medicalSupplyCrate_advanced",
    "ACE_medicalSupplyCrate",
    "ACE_Box_Chemlights",
    "ACE_Box_Ammo",
    "ACE_Box_82mm_Mo_Combo",
    "ACE_Box_82mm_Mo_HE",
    "ACE_Box_82mm_Mo_Illum",
    "ACE_Box_82mm_Mo_Smoke",
    "ACE_Box_Misc",
    "ACE_fastropingSupplyCrate",
    "VirtualReammoBox_camonet_F",
    "VirtualReammoBox_small_F",
    "Box_IND_Ammo_F",
    "Box_T_East_Ammo_F",
    "Box_East_Ammo_F",
    "Box_EAF_Ammo_F",
    "Box_Syndicate_Ammo_F",
    "Box_IND_Wps_F",
    "Box_T_East_Wps_F",
    "Box_East_Wps_F",
    "Box_EAF_Wps_F",
    "Box_T_NATO_Wps_F",
    "Box_NATO_Wps_F",
    "Box_Syndicate_Wps_F",
    "UK3CB_Cocaine_Pallet_Wrapped_Black",
    "UK3CB_Cocaine_Pallet_Wrapped_Blue",
    "UK3CB_Cocaine_Pallet_Wrapped_Green",
    "UK3CB_Cocaine_Pallet_Wrapped",
    "UK3CB_Cocaine_Pallet_Wrapped_IDAP_01",
    "UK3CB_Cocaine_Pallet_Wrapped_IDAP_02",
    "UK3CB_Cocaine_Pallet_Torn_Black",
    "UK3CB_Cocaine_Pallet_Torn",
    "UK3CB_Cocaine_Pallet_Torn_IDAP_01",
    "UK3CB_Cocaine_Pallet_Torn_IDAP_02",
    "Box_AAF_Equip_F",
    "Box_CSAT_Equip_F",
    "Box_IDAP_Equip_F",
    "Box_EAF_Equip_F",
    "Box_NATO_Equip_F",
    "Box_IED_Exp_F",
    "Box_IND_AmmoOrd_F",
    "Box_East_AmmoOrd_F",
    "Box_IDAP_AmmoOrd_F",
    "Box_EAF_AmmoOrd_F",
    "Box_NATO_AmmoOrd_F",
    "Box_FIA_Ammo_F",
    "Box_FIA_Support_F",
    "Box_FIA_Wps_F",
    "Box_IND_Grenades_F",
    "Box_East_Grenades_F",
    "Box_EAF_Grenades_F",
    "Box_NATO_Grenades_F",
    "Box_IND_WpsLaunch_F",
    "Box_East_WpsLaunch_F",
    "Box_EAF_WpsLaunch_F",
    "Box_NATO_WpsLaunch_F",
    "Box_Syndicate_WpsLaunch_F",
    "rhs_weapons_crate_ak_ammo_545x39",
    "rhs_weapons_crate_ak_ammo_545x39_standard",
    "rhs_weapons_crate_ak",
    "rhs_mags_crate",
    "rhs_gear_crate",
    "rhs_launcher_crate",
    "rhs_spec_weapons_crate",
    "rhs_weapon_crate",
    "rhsgref_weapons_crate",
    "Box_EAF_Uniforms_F",
    "Box_AAF_Uniforms_F",
    "Box_CSAT_Uniforms_F",
    "Box_IDAP_Uniforms_F",
    "Box_NATO_Uniforms_F",
    "VirtualReammoBox_F",
    "Box_IND_AmmoVeh_F",
    "Box_East_AmmoVeh_F",
    "Box_EAF_AmmoVeh_F",
    "Box_NATO_AmmoVeh_F",
    "Box_IND_WpsSpecial_F",
    "Box_T_East_WpsSpecial_F",
    "Box_East_WpsSpecial_F",
    "Box_EAF_WpsSpecial_F",
    "Box_T_NATO_WpsSpecial_F",
    "Box_NATO_WpsSpecial_F",
    "Box_IND_Support_F",
    "Box_East_Support_F",
    "Box_EAF_Support_F",
    "Box_NATO_Support_F",
    "I_supplyCrate_F",
    "O_supplyCrate_F",
    "C_T_supplyCrate_F",
    "C_supplyCrate_F",
    "IG_supplyCrate_F",
    "Box_GEN_Equip_F",
    "C_IDAP_supplyCrate_F",
    "I_EAF_supplyCrate_F",
    "B_supplyCrate_F",
    "CargoNet_01_box_F",
    "B_CargoNet_01_ammo_F",
    "CargoNet_01_barrels_F",
    "B_Slingload_01_Ammo_F",
    "B_Slingload_01_Cargo_F",
    "B_Slingload_01_Fuel_F",
    "B_Slingload_01_Medevac_F",
    "B_Slingload_01_Repair_F",
    "Land_Pod_Heli_Transport_04_ammo_F",
    "Land_Pod_Heli_Transport_04_box_F",
    "Land_Pod_Heli_Transport_04_fuel_F",
    "Land_Pod_Heli_Transport_04_repair_F",
    "FlexibleTank_01_forest_F",
    "FlexibleTank_01_sand_F",
    "Land_CargoBox_V1_F",
    "Land_Cargo20_EMP_F",
    "Land_Cargo20_EMP_Training_F",
    "Land_Cargo20_IDAP_F",
    "Land_Cargo20_blue_F",
    "Land_Cargo20_brick_red_F",
    "Land_Cargo20_cyan_F",
    "Land_Cargo20_grey_F",
    "Land_Cargo20_light_blue_F",
    "Land_Cargo20_military_green_F",
    "Land_Cargo20_orange_F",
    "Land_Cargo20_red_F",
    "Land_Cargo20_sand_F",
    "Land_Cargo20_white_F",
    "Land_Cargo20_yellow_F",
    "Land_Cargo10_military_green_F",
    "Land_Cargo10_blue_F",
    "Land_Cargo10_brick_red_F",
    "Land_Cargo10_cyan_F",
    "Land_Cargo10_grey_F",
    "Land_Cargo10_light_blue_F",
    "Land_Cargo10_light_green_F",
    "Land_Cargo10_orange_F",
    "Land_Cargo10_red_F",
    "Land_Cargo10_sand_F",
    "Land_Cargo10_white_F",
    "Land_Cargo10_yellow_F",
    "Land_WaterTank_F",
    "Land_WaterBarrel_F",
    "Land_FoodSacks_01_large_brown_F",
    "Land_FoodSacks_01_large_brown_idap_F",
    "Land_FoodSacks_01_large_white_idap_F",
    "Land_PaperBox_01_open_water_F",
    "Land_WaterBottle_01_stack_F",
    "Land_PaperBox_01_small_stacked_F",
    "Land_PaperBox_01_open_boxes_F",
    "Land_PaperBox_01_open_empty_F"
];

_actionMain = ["x5r_actions_crateLoad","Load in closest vehicle (ViV)","",{
	_carrier = (nearestObjects [_target, ["Car","Air"], 30]) select 0;
	if (isNil "_carrier") then {hint "No vehicle found";exit;};
	_check = _carrier canVehicleCargo _target;
	_carrierNameStr = getText (configOf _carrier >> "displayName");
	if (_check select 0) then {
		[10, [_target,_carrier], {
			params ["_args", "_elapsedTime", "_totalTime"];
   			_args params ["_target","_carrier"];
			_carrier setVehicleCargo _target;
		}, {}, format ["Loading cargo into %1...", _carrierNameStr]] call ace_common_fnc_progressBar;		
	}
	else {
		if (_check select 1) then {
			hint format ["%1\ndoesn't have enough free space to load the cargo\n\nLoading cargo in a different order might help", _carrierNameStr];
		} else {
			hint format ["%1's cargo area\nis too small to load this cargo", _carrierNameStr];
		};
	}; 
},{(isNull isVehicleCargo _target) && !(_target getVariable ["x5r_tags_vivDisabled",false])},{}] call ace_interact_menu_fnc_createAction;
{
	[_x, 0, ["ACE_MainActions"], _actionMain] call ace_interact_menu_fnc_addActionToClass;
} forEach _crates;
